// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SwiftRTOW",
    defaultLocalization: "en",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "SwiftRTOW",
            targets: ["AppModule"],
            bundleIdentifier: "com.otabuzzman.swiftrtow.ios",
            teamIdentifier: "28FV44657B",
            displayVersion: "1.0.4",
            bundleVersion: "20",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "SwiftRTOW wants to save render results in Photos.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("Settings.bundle")
            ],
            swiftSettings: [
                .unsafeFlags([], .when(configuration: .debug))
            ]
        )
    ]
)
